
version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    env_file:
      - .env.test
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.test
