
version: "3"
services:
  postgres:
    image: postgres:15
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "8080:80"
    env_file:
      -.env
  call-billing-api:
    image: call-billing-api
    build:
     dockerfile: ./Dockerfile
     context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge